// Category
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";

// Brand
export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const GET_ONE_BRAND = "GET_ONE_BRAND";

// subCategory
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

// Product
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCTS_LIKE = "GET_PRODUCTS_LIKE";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

// Auth
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

// Rate
export const CREATE_REVIEW = "CREATE_REVIEW";
export const ALL_REVIEW_PRODUCT = "ALL_REVIEW_PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";

// WhisList
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const USER_WISHLIST = "USER_WISHLIST";

// Coupon
export const ADD_COUPON = "ADD_COUPON";
export const GET_ALL_COUPON = "GET_ALL_COUPON";
export const GET_ONE_COUPON = "GET_ONE_COUPON";
export const EDIT_COUPON = "EDIT_COUPON";
export const DELTET_COUPON = "DELTET_COUPON";

// UserAddresses
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";
export const GET_ALL_USER_ADDRESS = "GET_ALL_USER_ADDRESS";
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";
export const GET_ONE_USER_ADDRESS = "GET_ONE_USER_ADDRESS";
export const EDIT_USER_ADDRESS = "EDIT_USER_ADDRESS";

// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_ALL_USER_CART = "GET_ALL_USER_CART";
export const CLEAR_ALL_USER_CART = "CLEAR_ALL_USER_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const UPDATE_ITEM_FROM_CART = "UPDATE_ITEM_FROM_CART";
export const APPALY_COUPON_CART = "APPALY_COUPON_CART";

// Error
export const GET_ERROR = "GET_ERROR";
